# Generated by Django 3.2.4 on 2021-06-20 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_first_migrations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='namd',
            new_name='name',
        ),
    ]
